# This playbook installs and configures docker
- hosts: "{{hosts}}"
  sudo: True

  tasks:
    - name: install docker
      apt: name=docker.io

    - name: change fs driver to devicemapper
      lineinfile: dest=/etc/default/docker create=yes line="DOCKER_OPTS=\"--storage-driver=devicemapper\""
