# This playbook installs and configures maven
- hosts: "{{hosts}}"

  tasks:
    - name: install maven
      sudo: True
      apt: name=maven

    - name: create .m2 dir
      file: path=/home/{{ansible_ssh_user}}/.m2 state=directory
