# This playbook installs and configures sbt
- hosts: "{{hosts}}"
  sudo: True

  tasks:
    - name: install sbt
      get_url: url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar dest=/usr/bin/sbt-launch.jar

    - name: sbt launcher script (1)
      lineinfile: dest=/usr/bin/sbt create=yes line="SBT_OPTS=\"-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M\""

    - name: sbt launcher script (2)
      lineinfile: dest=/usr/bin/sbt create=yes line="java $SBT_OPTS -jar `dirname $0`/sbt-launch.jar \"$@\""

    - name: sbt script mode to executable
      file: path=/usr/bin/sbt mode=0777
